# Generated by Django 6.1 on 2026-08-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شناسه پرداخت درگاه')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پرداخت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید پرداخت')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
