# Generated by Django 6.1 on 2026-08-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Authority'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref ID'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
